#!/usr/bin/env python3
"""Bake Natural Earth's 1:110m land polygons into src/landmask.h.

720x360 one-bit equirectangular mask (0.5 degree cells), 32,400 bytes in flash.
Row 0 is +90 latitude, column 0 is -180 longitude, MSB first. Pure stdlib: a
scanline even-odd fill, so holes (lakes) and islands both come out right.

    python3 tools/make-landmask.py ne_110m_land.geojson

Source: https://github.com/nvkelso/natural-earth-vector/blob/master/geojson/ne_110m_land.geojson
(public domain). Committed output is fine at 32KB; this script is the source.
"""
import json, sys, os

W, H = 720, 360
src = sys.argv[1] if len(sys.argv) > 1 else "ne_110m_land.geojson"
out = os.path.join(os.path.dirname(__file__), "..", "src", "landmask.h")

rings = []
for f in json.load(open(src))["features"]:
    g = f["geometry"]
    polys = g["coordinates"] if g["type"] == "Polygon" else [p for mp in g["coordinates"] for p in mp]
    rings.extend(polys)

# Edge list in cell coordinates: x = (lon+180)*2, y = (90-lat)*2.
edges = []
for ring in rings:
    pts = [((lon + 180.0) * W / 360.0, (90.0 - lat) * H / 180.0) for lon, lat in ring]
    for (x0, y0), (x1, y1) in zip(pts, pts[1:] + pts[:1]):
        if y0 != y1:
            edges.append((min(y0, y1), max(y0, y1), x0, y0, x1, y1))

rows = []
for r in range(H):
    yc = r + 0.5
    xs = []
    for ylo, yhi, x0, y0, x1, y1 in edges:
        if ylo <= yc < yhi:
            xs.append(x0 + (yc - y0) * (x1 - x0) / (y1 - y0))
    xs.sort()
    row = bytearray(W // 8)
    for a, b in zip(xs[0::2], xs[1::2]):
        for c in range(max(0, int(a + 0.5)), min(W, int(b + 0.5))):
            row[c >> 3] |= 0x80 >> (c & 7)
    rows.append(row)

land = sum(bin(b).count("1") for row in rows for b in row)
with open(out, "w") as f:
    f.write("// Generated by tools/make-landmask.py from Natural Earth 1:110m land. Do not edit.\n")
    f.write("// 720x360 one-bit equirectangular: row 0 = +90 lat, col 0 = -180 lon, MSB first.\n")
    f.write("#pragma once\n#include <stdint.h>\n")
    f.write(f"#define LANDMASK_W {W}\n#define LANDMASK_H {H}\n")
    f.write(f"static const uint8_t LANDMASK[{H} * {W // 8}] = {{\n")
    for row in rows:
        f.write("  " + ",".join(f"0x{b:02x}" for b in row) + ",\n")
    f.write("};\n")
print(f"{out}: {land} land cells of {W*H} ({100*land/(W*H):.1f}%)")
# Print a thumbnail so a broken fill is obvious without a viewer.
for r in range(0, H, 12):
    print("".join("#" if rows[r][c >> 3] & (0x80 >> (c & 7)) else "." for c in range(0, W, 6)))
