/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppsIndexRouteImport } from './routes/apps.index'
import { Route as AppsAppRouteImport } from './routes/apps.$app'
import { Route as BoardsBoardRouteImport } from './routes/boards.$board'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppRoute = AppsAppRouteImport.update({
  id: '/apps/$app',
  path: '/apps/$app',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardRoute = BoardsBoardRouteImport.update({
  id: '/boards/$board',
  path: '/boards/$board',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/apps/$app': typeof AppsAppRoute
  '/boards/$board': typeof BoardsBoardRoute
  '/apps/': typeof AppsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/apps/$app': typeof AppsAppRoute
  '/boards/$board': typeof BoardsBoardRoute
  '/apps': typeof AppsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/apps/$app': typeof AppsAppRoute
  '/boards/$board': typeof BoardsBoardRoute
  '/apps/': typeof AppsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/apps/$app' | '/boards/$board' | '/apps/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/apps/$app' | '/boards/$board' | '/apps'
  id:
    '__root__' | '/' | '/dashboard' | '/apps/$app' | '/boards/$board' | '/apps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  AppsAppRoute: typeof AppsAppRoute
  BoardsBoardRoute: typeof BoardsBoardRoute
  AppsIndexRoute: typeof AppsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$app': {
      id: '/apps/$app'
      path: '/apps/$app'
      fullPath: '/apps/$app'
      preLoaderRoute: typeof AppsAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$board': {
      id: '/boards/$board'
      path: '/boards/$board'
      fullPath: '/boards/$board'
      preLoaderRoute: typeof BoardsBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  AppsAppRoute: AppsAppRoute,
  BoardsBoardRoute: BoardsBoardRoute,
  AppsIndexRoute: AppsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
